'------------------------------------------------------------------------------
' <auto-generated>
'     DataObjects.Net Entity Model Designer
'     Template version: 1.0.4.0
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Imports Xtensive.Core
Imports Xtensive.Orm

Namespace DONet.Model.Designer.ModelTests.VB
    Public Partial Class Address
    Inherits Xtensive.Orm.Structure
        
        #Region "Scalar Properties"
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Validation.RangeConstraint(Min:=CSByte(0),Max:=CSByte(50))>
        <Xtensive.Orm.Key>
        Public Overridable Property SByteField as SByte
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property Int16Field as Short
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property Int32Field as Integer
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property Int64Field as Long
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property ByteField as Byte
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property UInt16Field as UShort
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property UInt32Field as UInteger
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property UInt64Field as ULong
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Validation.FutureConstraint>
        <Xtensive.Orm.Validation.PastConstraint(Mode:=Xtensive.Orm.Validation.ConstrainMode.OnValidate)>
        <Xtensive.Orm.Key>
        Public Overridable Property DateTimeField as Date
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key(Direction:=Xtensive.Core.Direction.Default,Position:=0)>
        Public Overridable Property GuidField as System.Guid
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property ByteArrayField as Byte()
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property StringField as String
        
        #End Region
    End Class
End Namespace
