'------------------------------------------------------------------------------
' <auto-generated>
'     DataObjects.Net Entity Model Designer
'     Template version: 1.0.4.0
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Imports Xtensive.Core
Imports Xtensive.Orm

Namespace MyEntityModel.Entities
    <Xtensive.Orm.HierarchyRoot>
    <Xtensive.Orm.Index("Name",Unique:=true,Name:="idxName")>
    <Xtensive.Orm.Index("Age:DESC")>
    Public NotInheritable Partial Class EntityBaseWithHistory
    Inherits EntityBase
    Implements MyEntityModel.Interfaces.IEntityWithHistory
        
        #Region "Scalar Properties"
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key(Position:=5)>
        Public Property Id as Integer Implements MyEntityModel.Interfaces.IEntity.Id
        
        <Xtensive.Orm.Field(DefaultValue:=Nothing,Indexed:=true,LazyLoad:=true,Length:=512,NullableOnUpgrade:=true)>
        <Xtensive.Orm.FieldMapping("sMore")>
        <Xtensive.Orm.Version(Xtensive.Orm.VersionMode.Auto)>
        <Xtensive.Orm.TypeDiscriminator>
        <Xtensive.Orm.Validation.EmailConstraint(Mode:=Xtensive.Orm.Validation.ConstrainMode.OnSetValue,Message:="Email is invalid")>
        <Xtensive.Orm.Validation.LengthConstraint(Mode:=Xtensive.Orm.Validation.ConstrainMode.OnValidate,Message:="Length is invalid",Min:=0,Max:=400)>
        <Xtensive.Orm.Validation.NotEmptyConstraint>
        <Xtensive.Orm.Validation.NotNullConstraint>
        <Xtensive.Orm.Validation.NotNullOrEmptyConstraint>
        Public Property More as String
        
        #End Region
        
        #Region "Navigation Properties"
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Association(PairTo:="Owner")>
        Public Property HistoryItems as MyEntityModel.TypedEntitySets.HistoryEntitySet Implements MyEntityModel.Interfaces.IEntityWithHistory.HistoryItems
        
        #End Region
        
        #Region "Inherited Scalar Properties"
        
        <Xtensive.Orm.Field>
        Public Property OId as System.Nullable(Of Byte) Implements MyEntityModel.Interfaces.IEntity.OId
        
        <Xtensive.Orm.Field(DefaultValue:=123456789R)>
        <Xtensive.Orm.Validation.EmailConstraint(Mode:=Xtensive.Orm.Validation.ConstrainMode.OnSetValue)>
        <Xtensive.Orm.Validation.LengthConstraint(Message:="Wrong Age",Min:=1,Max:=99)>
        Public Property Age as String
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Version(Xtensive.Orm.VersionMode.Skip)>
        Public Property ScalarProperty4 as String
        
        #End Region
        
        #Region "Constructors"
        
        Public  Sub New(ByVal session As Xtensive.Orm.Session)
        	MyBase.New(session)
        End Sub
        
        Public  Sub New()
        	MyBase.New()
        End Sub
        
        Public  Sub New(ByVal session As Xtensive.Orm.Session,id As Integer)
        	MyBase.New(session, id)
        End Sub
        
        #End Region
        
    End Class
End Namespace
