'------------------------------------------------------------------------------
' <auto-generated>
'     DataObjects.Net Entity Model Designer
'     Template version: 1.0.4.0
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Imports Xtensive.Core
Imports Xtensive.Orm

Namespace MyEntityModel.TypedEntitySets
    Public Partial Class HistoryEntitySet
    Inherits Xtensive.Orm.EntitySet(Of MyEntityModel.Interfaces.IHistory)
        
        #Region "Constructors"
        
        Protected Sub New(owner As Xtensive.Orm.Entity, field As Xtensive.Orm.Model.FieldInfo)
        	MyBase.New(owner, field)
        End Sub
        
        Protected Sub New(info As System.Runtime.Serialization.SerializationInfo, context As System.Runtime.Serialization.StreamingContext)
        	MyBase.New(info, context)
        End Sub
        
        #End Region
        
    End Class
End Namespace
