//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
namespace MyEntityModel
{
    [System.Runtime.Serialization.DataContractAttribute]
    public partial class CarDto: MyEntityModel.Entities.EntityBaseDto
    {
        
        #region Scalar Properties
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual int SuperKey
        {
            get;
            set;
        }
        
        #endregion Scalar Properties
        
        #region Navigation Properties
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual System.Collections.Generic.HashSet<CarDto> SimilarCars
        {
            get;
            set;
        }
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual PersonDto Owner
        {
            get;
            set;
        }
        
        #endregion Navigation Properties
        
        #region Constructors
        
        
        public CarDto()
        {
        	this.SimilarCars = new System.Collections.Generic.HashSet<CarDto>();
        	this.Owner = new PersonDto();
        }
        
        public CarDto(int superkey,PersonDto owner,int id): this()
        {
        	this.SuperKey = superkey;
        	this.Owner = owner;
        	this.Id = id;
        }
        
        #endregion Constructors
        
        #region Implementation of IObjectDto
        
        public override void UpdateKeyFields(IObjectDto sourceDto)
        {
        	base.UpdateKeyFields(sourceDto);
        	if (sourceDto is CarDto)
        	{
        		var _sourceDto = (CarDto)sourceDto;
        		this.SuperKey = _sourceDto.SuperKey;
        		this.Owner = (PersonDto)DtoUtils.Clone(_sourceDto.Owner);
        	}
        }
        
        #endregion
    }
}
