//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;

public static class DtoUtils
{
	public static T Clone<T>(T obj) where T : class
    {
		T result;
		using(MemoryStream serializationStream = new MemoryStream())
        {
			new BinaryFormatter().Serialize(serializationStream, obj);
			serializationStream.Position = 0;
			result = (T)new BinaryFormatter().Deserialize(serializationStream);
			serializationStream.Close();
		}
		
        return result;
    }
}
