//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
namespace MyEntityModel.Entities
{
    [System.Runtime.Serialization.DataContractAttribute]
    public partial class EntityBaseDto: MyEntityModel.Interfaces.IEntityDto
    {
        
        #region Scalar Properties
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual int Id
        {
            get;
            set;
        }
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual string Age
        {
            get;
            set;
        }
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual string ScalarProperty4
        {
            get;
            set;
        }
        
        #endregion Scalar Properties
        
        #region Inherited Scalar Properties
        
        public virtual System.Nullable<byte> OId
        {
            get;
            set;
        }
        
        #endregion Inherited Scalar Properties
        
        #region Constructors
        
        
        public EntityBaseDto()
        {}
        public EntityBaseDto(int id): this()
        {
        	this.Id = id;
        }
        
        #endregion Constructors
        
        
        #region Implementation of IObjectDto
        
        public IObjectDto OriginalObject { get; set; }
        
        public string _MappingKey { get; set; }
        
        public virtual void UpdateKeyFields(IObjectDto sourceDto)
        {
        	if (sourceDto is EntityBaseDto)
        	{
        		var _sourceDto = (EntityBaseDto)sourceDto;
        		this.Id = _sourceDto.Id;
        	}
        }
        
        #endregion
    }
}
