//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
namespace MyEntityModel.Entities
{
    [System.Runtime.Serialization.DataContractAttribute]
    public partial class EntityBaseWithHistoryDto: EntityBaseDto,MyEntityModel.Interfaces.IEntityWithHistoryDto
    {
        
        #region Scalar Properties
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual int Id
        {
            get;
            set;
        }
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual string More
        {
            get;
            set;
        }
        
        #endregion Scalar Properties
        
        #region Navigation Properties
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual MyEntityModel.TypedEntitySets.HistoryEntitySetDto HistoryItems
        {
            get;
            set;
        }
        
        #endregion Navigation Properties
        
        #region Constructors
        
        
        public EntityBaseWithHistoryDto()
        {
        	this.HistoryItems = new MyEntityModel.TypedEntitySets.HistoryEntitySetDto();
        }
        
        public EntityBaseWithHistoryDto(int id): this()
        {
        	this.Id = id;
        }
        
        #endregion Constructors
        
    }
}
