//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public interface IObjectDto
{
    [System.Xml.Serialization.XmlIgnore]
    IObjectDto OriginalObject { get; set; }
	
	[System.Runtime.Serialization.DataMember]
	string _MappingKey { get;set; }
	
	void UpdateKeyFields(IObjectDto sourceDto);
}
