//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
namespace MyEntityModel
{
    [System.Runtime.Serialization.DataContractAttribute]
    public partial class PersonDto: MyEntityModel.Entities.EntityBaseDto
    {
        
        #region Navigation Properties
        
        [System.Runtime.Serialization.DataMemberAttribute]
        public virtual System.Collections.Generic.HashSet<CarDto> Cars
        {
            get;
            set;
        }
        
        #endregion Navigation Properties
        
        #region Constructors
        
        
        public PersonDto()
        {
        	this.Cars = new System.Collections.Generic.HashSet<CarDto>();
        }
        
        public PersonDto(int id): this()
        {
        	this.Id = id;
        }
        
        #endregion Constructors
        
    }
}
