'------------------------------------------------------------------------------
' <auto-generated>
'     DataObjects.Net Entity Model Designer
'     Template version: 1.0.4.0
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Imports Xtensive.Core
Imports Xtensive.Orm

Namespace Debugging.VB
    <Xtensive.Orm.HierarchyRoot>
    Public MustInherit Partial Class Entity1
    Inherits Xtensive.Orm.Entity
        
        #Region "Scalar Properties"
        
        <Xtensive.Orm.Field>
        <Xtensive.Orm.Key>
        Public Overridable Property Id as Integer
        
        <Xtensive.Orm.Field(Indexed:=true,Length:=123)>
        Public Overridable Property Name as String
        
        #End Region
        
        #Region "Constructors"
        
        Public  Sub New(ByVal session As Xtensive.Orm.Session)
        	MyBase.New(session)
        End Sub
        
        Public  Sub New()
        	MyBase.New()
        End Sub
        
        Public  Sub New(ByVal session As Xtensive.Orm.Session,id As Integer)
        	MyBase.New(session, id)
        End Sub
        
        #End Region
        
    End Class
End Namespace
