//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Xtensive.Core;
using Xtensive.Orm;
namespace TXSoftware.DataObjectsNetEntityModel.Debugging
{
    [Xtensive.Orm.HierarchyRoot]
    [Xtensive.Orm.TableMapping("tUser")]
    [System.SerializableAttribute]
    public partial class User: Xtensive.Orm.Entity
    {
        
        #region Scalar Properties
        
        [Xtensive.Orm.Field]
        [Xtensive.Orm.Key]
        public virtual int Id
        {
            get;
            private set;
        }
        
        #endregion Scalar Properties
        
        #region Navigation Properties
        
        [Xtensive.Orm.Field]
        public virtual Address Address1
        {
            get;
            set;
        }
        
        #endregion Navigation Properties
        
        #region Constructors
        
        public User(Xtensive.Orm.Session session) : base(session)
        {}
        
        public User()
        {}
        public User(Xtensive.Orm.Session session,int id) : base(session,id)
        {}
        protected User(Xtensive.Orm.Session session,int id, params System.Object[] values) : base(session,id, values)
        {}
        
        #endregion Constructors
        
    }
}
