//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using Xtensive.Core;
using Xtensive.Orm;

namespace MyEntityModel.Entities
{
    [Xtensive.Orm.HierarchyRoot]
    [Xtensive.Orm.Index("Name",Unique=true,Name="idxName")]
    [Xtensive.Orm.Index("Age:DESC")]
    public partial class EntityBaseWithHistory: EntityBase,MyEntityModel.Interfaces.IEntityWithHistory
    {
        
        #region Scalar Properties
        
        [Xtensive.Orm.Field]
        [Xtensive.Orm.Key(Position=5)]
        public virtual int Id
        {
            get;
            private set;
        }
        
        [Xtensive.Orm.Field(DefaultValue=null,Indexed=true,LazyLoad=true,Length=512,NullableOnUpgrade=true)]
        [Xtensive.Orm.FieldMapping("sMore")]
        [Xtensive.Orm.Version(Xtensive.Orm.VersionMode.Auto)]
        [Xtensive.Orm.TypeDiscriminator]
        [Xtensive.Orm.Validation.EmailConstraint(Mode=Xtensive.Orm.Validation.ConstrainMode.OnSetValue,Message="Email is invalid")]
        [Xtensive.Orm.Validation.LengthConstraint(Mode=Xtensive.Orm.Validation.ConstrainMode.OnValidate,Message="Length is invalid",Min=0,Max=400)]
        [Xtensive.Orm.Validation.NotEmptyConstraint]
        [Xtensive.Orm.Validation.NotNullConstraint]
        [Xtensive.Orm.Validation.NotNullOrEmptyConstraint]
        public virtual string More
        {
            get;
            set;
        }
        
        #endregion Scalar Properties
        
        #region Navigation Properties
        
        [Xtensive.Orm.Field]
        [Xtensive.Orm.Association(PairTo="Owner")]
        public virtual MyEntityModel.TypedEntitySets.HistoryEntitySet HistoryItems
        {
            get;
            private set;
        }
        
        #endregion Navigation Properties
        
        #region Inherited Scalar Properties
        
        [Xtensive.Orm.Field]
        public virtual System.Nullable<byte> OId
        {
            get;
            set;
        }
        
        [Xtensive.Orm.Field(DefaultValue=123456789D)]
        [Xtensive.Orm.Validation.EmailConstraint(Mode=Xtensive.Orm.Validation.ConstrainMode.OnSetValue)]
        [Xtensive.Orm.Validation.LengthConstraint(Message="Wrong Age",Min=1,Max=99)]
        public virtual string Age
        {
            get;
            set;
        }
        
        [Xtensive.Orm.Field]
        [Xtensive.Orm.Version(Xtensive.Orm.VersionMode.Skip)]
        public virtual string ScalarProperty4
        {
            get;
            set;
        }
        
        #endregion Inherited Scalar Properties
    }
}
