//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "dom";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DataObjects.Net Entity Model Designer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"TX Software";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DONetEntityModelDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DONetEntityModelDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DONetEntityModelDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DONetEntityModelDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDONetEntityModelDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DONetEntityModelDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string DONetEntityModelDesignerPackageId = "429f3394-2cd0-4913-8ca0-0177f2b76897";
		
		// Editor factory identifier
		public const string DONetEntityModelDesignerEditorFactoryId = "7187e39a-cd41-48f4-bffd-1a7d310581e4";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DONetEntityModelDesignerModelExplorerToolWindowId = "4d9b3d9a-b0e6-4646-a612-1b2d3415ab2f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DONetEntityModelDesignerCommandSetId = "7c5c596f-9b3b-4a66-9d52-e78df9e993c6";
        
        // Model Explorer Menu Group
        public const string DONetEntityModelDesignerExplorerCommandSetId = "{29539a3c-5741-4377-b17c-5be1002853e2}";
    }
}