  //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using VSTextTemplatingHost = global::Microsoft.VisualStudio.TextTemplating.VSHost;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\10.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(DONetEntityModelDesignerExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(DONetEntityModelDesignerExplorerToolWindow), Constants.DONetEntityModelDesignerEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@DataObjects.Net Entity Model DesignerToolboxTab;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", "TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab",
					"@EntityToolboxItem;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					"TXSoftware.DataObjectsNetEntityModel.Dsl.EntityToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Entity", 
					"@EntityToolboxBitmap;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab",
					"@StructureToolboxItem;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					"TXSoftware.DataObjectsNetEntityModel.Dsl.StructureToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Structure", 
					"@StructureToolboxBitmap;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab",
					"@InheritanceToolboxItem;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					"TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"", 
					"@InheritanceToolboxBitmap;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab",
					"@InterfaceToolboxItem;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					"TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Interface", 
					"@InterfaceToolboxBitmap;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab",
					"@AssociationToolboxItem;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					"TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Association", 
					"@AssociationToolboxBitmap;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("TXSoftware.DataObjectsNetEntityModel.Dsl.DataObjects.Net Entity Model DesignerToolboxTab",
					"@TypedEntitySetToolboxItem;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					"TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"", 
					"@TypedEntitySetToolboxBitmap;TXSoftware.DataObjectsNetEntityModel.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(DONetEntityModelDesignerEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(DONetEntityModelDesignerEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"DONetEntityModelDesigner", typeof(DONetEntityModelDesignerEditorFactory))]
	internal abstract partial class DONetEntityModelDesignerPackageBase : DslShell::ModelingPackage
	{
		protected global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new DONetEntityModelDesignerEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			DONetEntityModelDesignerCommandSet commandSet = new DONetEntityModelDesignerCommandSet(this);
			commandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(DONetEntityModelDesignerExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideLoadKey("Standard", Constants.ProductVersion, Constants.ProductName, Constants.CompanyName, 1)]
    [VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[VSTextTemplatingHost::ProvideDirectiveProcessor(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDirectiveProcessor), global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDirectiveProcessor.DONetEntityModelDesignerDirectiveProcessorName, "A directive processor that provides access to DONetEntityModelDesigner files")]
	[global::System.Runtime.InteropServices.Guid(Constants.DONetEntityModelDesignerPackageId)]
	//[FileGenerationRegistrationAttribute(Constants.DONetEntityModelDesignerPackageId, "{87CFAA4A-2AEE-4967-AE38-58AB7CD49091}", "{" + Constants.DONetEntityModelDesignerEditorFactoryId + "}", typeof(TXSoftware.DataObjectsNetEntityModel.Dsl.DONetFileGenerator))]
	internal sealed partial class DONetEntityModelDesignerPackage : DONetEntityModelDesignerPackageBase
	{
	}
}