//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "TXSoftware.DataObjectsNetEntityModel.Dsl.EntityDiagram")]

namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainClass EntityDiagram
	/// Description for TXSoftware.DataObjectsNetEntityModel.Dsl.EntityDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("TXSoftware.DataObjectsNetEntityModel.Dsl.EntityDiagram.DisplayName", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.EntityDiagram.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e9b83bcb-ed9e-4841-a53a-203725382ffc")]
	public partial class EntityDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			CompartmentItemAddRule.ElementAdded(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			CompartmentItemDeleteRule.ElementDeleted(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			CompartmentItemChangeRule.ElementPropertyChanged(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, true /* repaint only */);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			if(connector is global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyTypeOfConnector)
			{
				// Method:
				// private DslDiagrams::NodeShape GetSourceShapeForStructurePropertyTypeOfConnector(StructurePropertyTypeOfConnector connector)
				// {
				// }
				// must be implemented in a partial class of EntityDiagram.  Given an instance of StructurePropertyTypeOfConnector,
				// the method should return the source shape for the connector.  This method should not return null.
				sourceShape = GetSourceShapeForStructurePropertyTypeOfConnector((global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyTypeOfConnector)connector);
			}
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Get the source role-player of the link that would be mapped by the given connector
		/// </summary>
		/// <param name="connector">The given connector.</param>
		/// <returns>The source role-player of the link that would be mapped by the given connector.</returns>
		protected override DslModeling::ModelElement GetSourceRolePlayerForLinkMappedByConnector(DslDiagrams::BinaryLinkShape connector)
		{
			StructurePropertyTypeOfConnector instanceOfStructurePropertyTypeOfConnector = connector as StructurePropertyTypeOfConnector;
			if (instanceOfStructurePropertyTypeOfConnector != null)
			{
				// The following method needs to be added in a partial class
				//   private DslModeling::ModelElement GetSourceRolePlayerForLinkMappedByStructurePropertyTypeOfConnector(StructurePropertyTypeOfConnector connector);
				return this.GetSourceRolePlayerForLinkMappedByStructurePropertyTypeOfConnector(instanceOfStructurePropertyTypeOfConnector);
			}
		
			// Fallthrough to base behavior
			return base.GetSourceRolePlayerForLinkMappedByConnector(connector);
		}
		
		/// <summary>
		/// Get the target role-player of the link that would be mapped by the given connector
		/// </summary>
		/// <param name="connector">The given connector.</param>
		/// <returns>The target role-player of the link that would be mapped by the given connector.</returns>
		protected override DslModeling::ModelElement GetTargetRolePlayerForLinkMappedByConnector(DslDiagrams::BinaryLinkShape connector)
		{
			// Fallthrough to base behavior
			return base.GetTargetRolePlayerForLinkMappedByConnector(connector);
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.Entity)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityShape newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBase)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseShape newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySet)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetShape newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.Interface)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceInheritInterfaces)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceInheritanceConnector newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceInheritanceConnector(this.Partition);
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseHasBaseType)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseInheritanceConnector newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseInheritanceConnector(this.Partition);
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyHasType)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyTypeOfConnector newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyTypeOfConnector(this.Partition);
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnector newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnector(this.Partition);
				return newShape;
			}
			if(element is global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetHasItemType)
			{
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetHasItemTypeConnector newShape = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetHasItemTypeConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape.DecoratorsInitialized += PersistentShapeDecoratorMap.OnDecoratorsInitialized;
			global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetShape.DecoratorsInitialized += TypedEntitySetShapeDecoratorMap.OnDecoratorsInitialized;
			global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape.DecoratorsInitialized += InterfaceShapeDecoratorMap.OnDecoratorsInitialized;
			global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseShape.DecoratorsInitialized += EntityBaseShapeDecoratorMap.OnDecoratorsInitialized;
			global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityShape.DecoratorsInitialized += EntityShapeDecoratorMap.OnDecoratorsInitialized;
			global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnector.DecoratorsInitialized += AssociationConnectorDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for PersistentShape.
		/// </summary>
		internal static partial class PersistentShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for PersistentShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TextName").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.TypeNameDomainPropertyId);
				propertyInfo.FilteringValues.Add("Entity");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconEntity").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.TypeNameDomainPropertyId);
				propertyInfo.FilteringValues.Add("Structure");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconStructure").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.TypeNameDomainPropertyId);
				propertyInfo.FilteringValues.Add("Interface");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconInterface").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.InheritsFromDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconInherit").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.TypeDescriptionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TextDescription").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType.TypeKindDomainPropertyId);
				propertyInfo.FilteringValues.Add("TypedEntitySet");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconTypedEntitySet").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for TypedEntitySetShape.
		/// </summary>
		internal static partial class TypedEntitySetShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for TypedEntitySetShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				PersistentShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for InterfaceShape.
		/// </summary>
		internal static partial class InterfaceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for InterfaceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				PersistentShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EntityBaseShape.
		/// </summary>
		internal static partial class EntityBaseShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EntityBaseShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				InterfaceShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EntityShape.
		/// </summary>
		internal static partial class EntityShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EntityShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				EntityBaseShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.Entity.IsHierarchyRootDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconHierarchyRoot").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AssociationConnector.
		/// </summary>
		internal static partial class AssociationConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AssociationConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations.SourceMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TextSourceMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations.TargetMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TextTargetMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceConnectAction inheritanceConnectAction;
		private global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnectAction associationConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerToolboxHelper.InheritanceFilterString))
				{
					if (this.inheritanceConnectAction == null)
					{
						this.inheritanceConnectAction = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceConnectAction(this);
						this.inheritanceConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.inheritanceConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerToolboxHelper.AssociationFilterString))
				{
					if (this.associationConnectAction == null)
					{
						this.associationConnectAction = new global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnectAction(this);
						this.associationConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.associationConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.inheritanceConnectAction != null)
					{
						this.inheritanceConnectAction.Dispose();
						this.inheritanceConnectAction = null;
					}
					if(this.associationConnectAction != null)
					{
						this.associationConnectAction.Dispose();
						this.associationConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// EntityDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe9b83bcb, 0xed9e, 0x4841, 0xa5, 0x3a, 0x20, 0x37, 0x25, 0x38, 0x2f, 0xfc);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EntityDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EntityDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.Entity), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.Interface), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySet), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyHasType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetHasItemType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceInheritInterfaces), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseHasBaseType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyHasType)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForStructurePropertyHasType(StructurePropertyHasType childLink)
					// {
					// }
					// must be implemented in a partial class of TXSoftware.DataObjectsNetEntityModel.Dsl.FixUpDiagram.  Given a child element link,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the connector created for this child.  If no connector should be created, the method should return null.
					parentElement = GetParentForStructurePropertyHasType((global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyHasType)childElement);
				} else
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.Entity)
				{
					parentElement = GetParentForEntity((global::TXSoftware.DataObjectsNetEntityModel.Dsl.Entity)childElement);
				} else
				if(childElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBase)
				{
					parentElement = GetParentForEntityBase((global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBase)childElement);
				} else
				if(childElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.Interface)
				{
					parentElement = GetParentForInterface((global::TXSoftware.DataObjectsNetEntityModel.Dsl.Interface)childElement);
				} else
				if(childElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySet)
				{
					parentElement = GetParentForTypedEntitySet((global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySet)childElement);
				} else
				if(childElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType)
				{
					parentElement = GetParentForPersistentType((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel GetParentForPersistentType( global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType root )
			{
				// Segments 0 and 1
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel result = root.EntityModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel GetParentForTypedEntitySet( global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType root )
			{
				// Segments 0 and 1
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel result = root.EntityModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel GetParentForEntity( global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType root )
			{
				// Segments 0 and 1
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel result = root.EntityModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel GetParentForInterface( global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType root )
			{
				// Segments 0 and 1
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel result = root.EntityModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel GetParentForEntityBase( global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType root )
			{
				// Segments 0 and 1
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModel result = root.EntityModel;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties)
				{
					global::System.Collections.IEnumerable elements = GetPersistentTypeForPersistentShapePropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties)e.ModelElement);
					UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "Properties", repaintOnly);
				}
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties)
				{
					global::System.Collections.IEnumerable elements = GetPersistentTypeForPersistentShapeNavigationPropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties)e.ModelElement);
					UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "NavigationProperties", repaintOnly);
				}
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes)
				{
					global::System.Collections.IEnumerable elements = GetInterfaceForInterfaceShapeIndexesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes)e.ModelElement);
					UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape), "Indexes", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetPersistentTypeForPersistentShapePropertiesFromLastLink(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties root)
			{
				// Segment 0
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType result = root.Properties;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetPersistentTypeForPersistentShapeProperties(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase root)
			{
				// Segments 1 and 0
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType result = root.PersistentType;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetPersistentTypeForPersistentShapeNavigationPropertiesFromLastLink(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties root)
			{
				// Segment 0
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType result = root.NavigationProperties;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetPersistentTypeForPersistentShapeNavigationProperties(global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty root)
			{
				// Segments 1 and 0
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentType result = root.PersistentTypeOfNavigationProperty;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetInterfaceForInterfaceShapeIndexesFromLastLink(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes root)
			{
				// Segment 0
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.Interface result = root.Indexes;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetInterfaceForInterfaceShapeIndexes(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex root)
			{
				// Segments 1 and 0
				global::TXSoftware.DataObjectsNetEntityModel.Dsl.Interface result = root.InterfaceOfIndex;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapePropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "Properties", repaintOnly);
				}
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeNavigationPropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "NavigationProperties", repaintOnly);
				}
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetInterfaceForInterfaceShapeIndexesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape), "Indexes", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase && e.DomainProperty.Id == global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeProperties((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "Properties", repaintOnly);
				}
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty && e.DomainProperty.Id == global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeNavigationProperties((global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "NavigationProperties", repaintOnly);
				}
				if(e.ModelElement is global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex && e.DomainProperty.Id == global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex.CalculatedNameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInterfaceForInterfaceShapeIndexes((global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape), "Indexes", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapePropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape compartmentShape = pel as global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapePropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "Properties", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeProperties((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "Properties", repaintOnly);
					}
				}
				if(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeNavigationPropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape compartmentShape = pel as global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[1].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeNavigationPropertiesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "NavigationProperties", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeNavigationProperties((global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "NavigationProperties", repaintOnly);
					}
				}
				if(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetInterfaceForInterfaceShapeIndexesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape compartmentShape = pel as global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInterfaceForInterfaceShapeIndexesFromLastLink((global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape), "Indexes", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInterfaceForInterfaceShapeIndexes((global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape), "Indexes", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeProperties((global::TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyBase)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "Properties", repaintOnly);
					}
				}
				if(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetPersistentTypeForPersistentShapeNavigationProperties((global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationProperty)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentShape), "NavigationProperties", repaintOnly);
					}
				}
				if(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetInterfaceForInterfaceShapeIndexes((global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityIndex)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceShape), "Indexes", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations.SourceMultiplicityDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnector.FindAssociationConnectorDecorator("TextSourceMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations.TargetMultiplicityDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::TXSoftware.DataObjectsNetEntityModel.Dsl.AssociationConnector.FindAssociationConnectorDecorator("TextTargetMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceInheritInterfaces), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityBaseHasBaseType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.StructurePropertyHasType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasAssociations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.TypedEntitySetHasItemType), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityDiagram diagram = linkShape.Diagram as global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
