//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainModel DONetEntityModelDesignerDomainModel
	/// DataObjects.Net Entity Model Designer
	/// </summary>
	[DslDesign::DisplayNameResource("TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel.DisplayName", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("99eed35b-b20e-4623-a645-6f62554bb450")]
	public partial class DONetEntityModelDesignerDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DONetEntityModelDesignerDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x99eed35b, 0xb20e, 0x4623, 0xa6, 0x45, 0x6f, 0x62, 0x55, 0x4b, 0xb4, 0x50);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DONetEntityModelDesignerDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(EntityModel),
				typeof(PersistentType),
				typeof(Entity),
				typeof(Structure),
				typeof(Interface),
				typeof(EntityBase),
				typeof(PropertyBase),
				typeof(ScalarProperty),
				typeof(NavigationProperty),
				typeof(StructureProperty),
				typeof(TypedEntitySet),
				typeof(EntityIndex),
				typeof(DomainType),
				typeof(EntityModelHasPersistentTypes),
				typeof(InterfaceInheritInterfaces),
				typeof(EntityBaseHasBaseType),
				typeof(StructurePropertyHasType),
				typeof(PersistentTypeHasProperties),
				typeof(PersistentTypeHasNavigationProperties),
				typeof(PersistentTypeHasAssociations),
				typeof(NavigationPropertyHasAssociation),
				typeof(TypedEntitySetHasItemType),
				typeof(InterfaceHasIndexes),
				typeof(NavigationPropertyHasTypedEntitySet),
				typeof(EntityModelHasDomainTypes),
				typeof(EntityDiagram),
				typeof(EntityBaseInheritanceConnector),
				typeof(InterfaceInheritanceConnector),
				typeof(StructurePropertyTypeOfConnector),
				typeof(AssociationConnector),
				typeof(TypedEntitySetHasItemTypeConnector),
				typeof(PersistentShape),
				typeof(TypedEntitySetShape),
				typeof(EntityShape),
				typeof(InterfaceShape),
				typeof(EntityBaseShape),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.FixUpDiagram),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DecoratorPropertyChanged),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.ConnectorRolePlayerChanged),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemAddRule),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemDeleteRule),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemRolePlayerChangeRule),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(EntityModel), "Namespace", EntityModel.NamespaceDomainPropertyId, typeof(EntityModel.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "ModelRoot", EntityModel.ModelRootDomainPropertyId, typeof(EntityModel.ModelRootPropertyHandler)),
				new DomainMemberInfo(typeof(EntityModel), "Version", EntityModel.VersionDomainPropertyId, typeof(EntityModel.VersionPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "Name", PersistentType.NameDomainPropertyId, typeof(PersistentType.NamePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "Namespace", PersistentType.NamespaceDomainPropertyId, typeof(PersistentType.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "TypeName", PersistentType.TypeNameDomainPropertyId, typeof(PersistentType.TypeNamePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "Access", PersistentType.AccessDomainPropertyId, typeof(PersistentType.AccessPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "InheritsFrom", PersistentType.InheritsFromDomainPropertyId, typeof(PersistentType.InheritsFromPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "InheritsFromName", PersistentType.InheritsFromNameDomainPropertyId, typeof(PersistentType.InheritsFromNamePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "TypeKind", PersistentType.TypeKindDomainPropertyId, typeof(PersistentType.TypeKindPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "TypeDescription", PersistentType.TypeDescriptionDomainPropertyId, typeof(PersistentType.TypeDescriptionPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "Documentation", PersistentType.DocumentationDomainPropertyId, typeof(PersistentType.DocumentationPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentType), "DataContract", PersistentType.DataContractDomainPropertyId, typeof(PersistentType.DataContractPropertyHandler)),
				new DomainMemberInfo(typeof(Entity), "HierarchyRootAttribute", Entity.HierarchyRootAttributeDomainPropertyId, typeof(Entity.HierarchyRootAttributePropertyHandler)),
				new DomainMemberInfo(typeof(Entity), "IsHierarchyRoot", Entity.IsHierarchyRootDomainPropertyId, typeof(Entity.IsHierarchyRootPropertyHandler)),
				new DomainMemberInfo(typeof(Entity), "KeyGenerator", Entity.KeyGeneratorDomainPropertyId, typeof(Entity.KeyGeneratorPropertyHandler)),
				new DomainMemberInfo(typeof(Entity), "TypeDiscriminatorValue", Entity.TypeDiscriminatorValueDomainPropertyId, typeof(Entity.TypeDiscriminatorValuePropertyHandler)),
				new DomainMemberInfo(typeof(Interface), "InheritInterfaces", Interface.InheritInterfacesDomainPropertyId, typeof(Interface.InheritInterfacesPropertyHandler)),
				new DomainMemberInfo(typeof(Interface), "InheritsIEntity", Interface.InheritsIEntityDomainPropertyId, typeof(Interface.InheritsIEntityPropertyHandler)),
				new DomainMemberInfo(typeof(EntityBase), "InheritanceModifier", EntityBase.InheritanceModifierDomainPropertyId, typeof(EntityBase.InheritanceModifierPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "Name", PropertyBase.NameDomainPropertyId, typeof(PropertyBase.NamePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "TypeName", PropertyBase.TypeNameDomainPropertyId, typeof(PropertyBase.TypeNamePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "PropertyAccess", PropertyBase.PropertyAccessDomainPropertyId, typeof(PropertyBase.PropertyAccessPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "IsBrowsable", PropertyBase.IsBrowsableDomainPropertyId, typeof(PropertyBase.IsBrowsablePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "Documentation", PropertyBase.DocumentationDomainPropertyId, typeof(PropertyBase.DocumentationPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "PropertyKind", PropertyBase.PropertyKindDomainPropertyId, typeof(PropertyBase.PropertyKindPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "FieldAttribute", PropertyBase.FieldAttributeDomainPropertyId, typeof(PropertyBase.FieldAttributePropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "IsInherited", PropertyBase.IsInheritedDomainPropertyId, typeof(PropertyBase.IsInheritedPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "Constraints", PropertyBase.ConstraintsDomainPropertyId, typeof(PropertyBase.ConstraintsPropertyHandler)),
				new DomainMemberInfo(typeof(PropertyBase), "DataMember", PropertyBase.DataMemberDomainPropertyId, typeof(PropertyBase.DataMemberPropertyHandler)),
				new DomainMemberInfo(typeof(ScalarProperty), "KeyAttribute", ScalarProperty.KeyAttributeDomainPropertyId, typeof(ScalarProperty.KeyAttributePropertyHandler)),
				new DomainMemberInfo(typeof(ScalarProperty), "Type", ScalarProperty.TypeDomainPropertyId, typeof(ScalarProperty.TypePropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "Multiplicity", NavigationProperty.MultiplicityDomainPropertyId, typeof(NavigationProperty.MultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "ReturnType", NavigationProperty.ReturnTypeDomainPropertyId, typeof(NavigationProperty.ReturnTypePropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "PairFrom", NavigationProperty.PairFromDomainPropertyId, typeof(NavigationProperty.PairFromPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "PairTo", NavigationProperty.PairToDomainPropertyId, typeof(NavigationProperty.PairToPropertyHandler)),
				new DomainMemberInfo(typeof(NavigationProperty), "KeyAttribute", NavigationProperty.KeyAttributeDomainPropertyId, typeof(NavigationProperty.KeyAttributePropertyHandler)),
				new DomainMemberInfo(typeof(EntityIndex), "Unique", EntityIndex.UniqueDomainPropertyId, typeof(EntityIndex.UniquePropertyHandler)),
				new DomainMemberInfo(typeof(EntityIndex), "FillFactor", EntityIndex.FillFactorDomainPropertyId, typeof(EntityIndex.FillFactorPropertyHandler)),
				new DomainMemberInfo(typeof(EntityIndex), "Name", EntityIndex.NameDomainPropertyId, typeof(EntityIndex.NamePropertyHandler)),
				new DomainMemberInfo(typeof(EntityIndex), "IndexName", EntityIndex.IndexNameDomainPropertyId, typeof(EntityIndex.IndexNamePropertyHandler)),
				new DomainMemberInfo(typeof(EntityIndex), "CalculatedName", EntityIndex.CalculatedNameDomainPropertyId, typeof(EntityIndex.CalculatedNamePropertyHandler)),
				new DomainMemberInfo(typeof(EntityIndex), "Fields", EntityIndex.FieldsDomainPropertyId, typeof(EntityIndex.FieldsPropertyHandler)),
				new DomainMemberInfo(typeof(DomainType), "Name", DomainType.NameDomainPropertyId, typeof(DomainType.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DomainType), "Namespace", DomainType.NamespaceDomainPropertyId, typeof(DomainType.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(DomainType), "FullName", DomainType.FullNameDomainPropertyId, typeof(DomainType.FullNamePropertyHandler)),
				new DomainMemberInfo(typeof(DomainType), "IsBuildIn", DomainType.IsBuildInDomainPropertyId, typeof(DomainType.IsBuildInPropertyHandler)),
				new DomainMemberInfo(typeof(DomainType), "BuildInID", DomainType.BuildInIDDomainPropertyId, typeof(DomainType.BuildInIDPropertyHandler)),
				new DomainMemberInfo(typeof(InterfaceInheritInterfaces), "BaseType", InterfaceInheritInterfaces.BaseTypeDomainPropertyId, typeof(InterfaceInheritInterfaces.BaseTypePropertyHandler)),
				new DomainMemberInfo(typeof(InterfaceInheritInterfaces), "DerivedType", InterfaceInheritInterfaces.DerivedTypeDomainPropertyId, typeof(InterfaceInheritInterfaces.DerivedTypePropertyHandler)),
				new DomainMemberInfo(typeof(EntityBaseHasBaseType), "BaseType", EntityBaseHasBaseType.BaseTypeDomainPropertyId, typeof(EntityBaseHasBaseType.BaseTypePropertyHandler)),
				new DomainMemberInfo(typeof(EntityBaseHasBaseType), "DerivedType", EntityBaseHasBaseType.DerivedTypeDomainPropertyId, typeof(EntityBaseHasBaseType.DerivedTypePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentTypeHasAssociations), "Name", PersistentTypeHasAssociations.NameDomainPropertyId, typeof(PersistentTypeHasAssociations.NamePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentTypeHasAssociations), "End1", PersistentTypeHasAssociations.End1DomainPropertyId, typeof(PersistentTypeHasAssociations.End1PropertyHandler)),
				new DomainMemberInfo(typeof(PersistentTypeHasAssociations), "End2", PersistentTypeHasAssociations.End2DomainPropertyId, typeof(PersistentTypeHasAssociations.End2PropertyHandler)),
				new DomainMemberInfo(typeof(PersistentTypeHasAssociations), "SourceMultiplicity", PersistentTypeHasAssociations.SourceMultiplicityDomainPropertyId, typeof(PersistentTypeHasAssociations.SourceMultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentTypeHasAssociations), "TargetMultiplicity", PersistentTypeHasAssociations.TargetMultiplicityDomainPropertyId, typeof(PersistentTypeHasAssociations.TargetMultiplicityPropertyHandler)),
				new DomainMemberInfo(typeof(TypedEntitySetHasItemType), "ResultTypeName", TypedEntitySetHasItemType.ResultTypeNameDomainPropertyId, typeof(TypedEntitySetHasItemType.ResultTypeNamePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentShape), "OutlineDashStyle", PersistentShape.OutlineDashStyleDomainPropertyId, typeof(PersistentShape.OutlineDashStylePropertyHandler)),
				new DomainMemberInfo(typeof(PersistentShape), "OutlineThickness", PersistentShape.OutlineThicknessDomainPropertyId, typeof(PersistentShape.OutlineThicknessPropertyHandler)),
				new DomainMemberInfo(typeof(PersistentShape), "FillColor", PersistentShape.FillColorDomainPropertyId, typeof(PersistentShape.FillColorPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(EntityModelHasPersistentTypes), "EntityModel", EntityModelHasPersistentTypes.EntityModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityModelHasPersistentTypes), "Element", EntityModelHasPersistentTypes.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(InterfaceInheritInterfaces), "SourceInheritInterface", InterfaceInheritInterfaces.SourceInheritInterfaceDomainRoleId),
				new DomainRolePlayerInfo(typeof(InterfaceInheritInterfaces), "TargetInheritByInterface", InterfaceInheritInterfaces.TargetInheritByInterfaceDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityBaseHasBaseType), "SourceEntityBase", EntityBaseHasBaseType.SourceEntityBaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityBaseHasBaseType), "TargetEntityBase", EntityBaseHasBaseType.TargetEntityBaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(StructurePropertyHasType), "StructureProperty", StructurePropertyHasType.StructurePropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(StructurePropertyHasType), "Structure", StructurePropertyHasType.StructureDomainRoleId),
				new DomainRolePlayerInfo(typeof(PersistentTypeHasProperties), "Properties", PersistentTypeHasProperties.PropertiesDomainRoleId),
				new DomainRolePlayerInfo(typeof(PersistentTypeHasProperties), "PersistentType", PersistentTypeHasProperties.PersistentTypeDomainRoleId),
				new DomainRolePlayerInfo(typeof(PersistentTypeHasNavigationProperties), "NavigationProperties", PersistentTypeHasNavigationProperties.NavigationPropertiesDomainRoleId),
				new DomainRolePlayerInfo(typeof(PersistentTypeHasNavigationProperties), "PersistentTypeOfNavigationProperty", PersistentTypeHasNavigationProperties.PersistentTypeOfNavigationPropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(PersistentTypeHasAssociations), "SourcePersistentType", PersistentTypeHasAssociations.SourcePersistentTypeDomainRoleId),
				new DomainRolePlayerInfo(typeof(PersistentTypeHasAssociations), "TargetPersistentType", PersistentTypeHasAssociations.TargetPersistentTypeDomainRoleId),
				new DomainRolePlayerInfo(typeof(NavigationPropertyHasAssociation), "NavigationProperty", NavigationPropertyHasAssociation.NavigationPropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(NavigationPropertyHasAssociation), "PersistentTypeHasAssociations", NavigationPropertyHasAssociation.PersistentTypeHasAssociationsDomainRoleId),
				new DomainRolePlayerInfo(typeof(TypedEntitySetHasItemType), "TypedEntitySet", TypedEntitySetHasItemType.TypedEntitySetDomainRoleId),
				new DomainRolePlayerInfo(typeof(TypedEntitySetHasItemType), "TypeOfItem", TypedEntitySetHasItemType.TypeOfItemDomainRoleId),
				new DomainRolePlayerInfo(typeof(InterfaceHasIndexes), "Indexes", InterfaceHasIndexes.IndexesDomainRoleId),
				new DomainRolePlayerInfo(typeof(InterfaceHasIndexes), "InterfaceOfIndex", InterfaceHasIndexes.InterfaceOfIndexDomainRoleId),
				new DomainRolePlayerInfo(typeof(NavigationPropertyHasTypedEntitySet), "OwnerNavigationProperty", NavigationPropertyHasTypedEntitySet.OwnerNavigationPropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(NavigationPropertyHasTypedEntitySet), "TypedEntitySet", NavigationPropertyHasTypedEntitySet.TypedEntitySetDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityModelHasDomainTypes), "EntityModel", EntityModelHasDomainTypes.EntityModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityModelHasDomainTypes), "DomainType", EntityModelHasDomainTypes.DomainTypeDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(24);
				createElementMap.Add(typeof(EntityModel), 0);
				createElementMap.Add(typeof(Entity), 1);
				createElementMap.Add(typeof(Structure), 2);
				createElementMap.Add(typeof(Interface), 3);
				createElementMap.Add(typeof(ScalarProperty), 4);
				createElementMap.Add(typeof(NavigationProperty), 5);
				createElementMap.Add(typeof(StructureProperty), 6);
				createElementMap.Add(typeof(TypedEntitySet), 7);
				createElementMap.Add(typeof(EntityIndex), 8);
				createElementMap.Add(typeof(DomainType), 9);
				createElementMap.Add(typeof(EntityDiagram), 10);
				createElementMap.Add(typeof(EntityBaseInheritanceConnector), 11);
				createElementMap.Add(typeof(InterfaceInheritanceConnector), 12);
				createElementMap.Add(typeof(StructurePropertyTypeOfConnector), 13);
				createElementMap.Add(typeof(AssociationConnector), 14);
				createElementMap.Add(typeof(TypedEntitySetHasItemTypeConnector), 15);
				createElementMap.Add(typeof(PersistentShape), 16);
				createElementMap.Add(typeof(TypedEntitySetShape), 17);
				createElementMap.Add(typeof(EntityShape), 18);
				createElementMap.Add(typeof(InterfaceShape), 19);
				createElementMap.Add(typeof(EntityBaseShape), 20);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new EntityModel(partition, propertyAssignments);
				// A constructor was not generated for Entity because it had HasCustomConstructor
				// set to true. Please provide the constructor below.
				case 1: return new Entity(partition, propertyAssignments);
				case 2: return new Structure(partition, propertyAssignments);
				case 3: return new Interface(partition, propertyAssignments);
				// A constructor was not generated for ScalarProperty because it had HasCustomConstructor
				// set to true. Please provide the constructor below.
				case 4: return new ScalarProperty(partition, propertyAssignments);
				// A constructor was not generated for NavigationProperty because it had HasCustomConstructor
				// set to true. Please provide the constructor below.
				case 5: return new NavigationProperty(partition, propertyAssignments);
				case 6: return new StructureProperty(partition, propertyAssignments);
				case 7: return new TypedEntitySet(partition, propertyAssignments);
				// A constructor was not generated for EntityIndex because it had HasCustomConstructor
				// set to true. Please provide the constructor below.
				case 8: return new EntityIndex(partition, propertyAssignments);
				case 9: return new DomainType(partition, propertyAssignments);
				case 10: return new EntityDiagram(partition, propertyAssignments);
				case 11: return new EntityBaseInheritanceConnector(partition, propertyAssignments);
				case 12: return new InterfaceInheritanceConnector(partition, propertyAssignments);
				case 13: return new StructurePropertyTypeOfConnector(partition, propertyAssignments);
				case 14: return new AssociationConnector(partition, propertyAssignments);
				case 15: return new TypedEntitySetHasItemTypeConnector(partition, propertyAssignments);
				case 16: return new PersistentShape(partition, propertyAssignments);
				case 17: return new TypedEntitySetShape(partition, propertyAssignments);
				case 18: return new EntityShape(partition, propertyAssignments);
				case 19: return new InterfaceShape(partition, propertyAssignments);
				case 20: return new EntityBaseShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12);
				createElementLinkMap.Add(typeof(EntityModelHasPersistentTypes), 0);
				createElementLinkMap.Add(typeof(InterfaceInheritInterfaces), 1);
				createElementLinkMap.Add(typeof(EntityBaseHasBaseType), 2);
				createElementLinkMap.Add(typeof(StructurePropertyHasType), 3);
				createElementLinkMap.Add(typeof(PersistentTypeHasProperties), 4);
				createElementLinkMap.Add(typeof(PersistentTypeHasNavigationProperties), 5);
				createElementLinkMap.Add(typeof(PersistentTypeHasAssociations), 6);
				createElementLinkMap.Add(typeof(NavigationPropertyHasAssociation), 7);
				createElementLinkMap.Add(typeof(TypedEntitySetHasItemType), 8);
				createElementLinkMap.Add(typeof(InterfaceHasIndexes), 9);
				createElementLinkMap.Add(typeof(NavigationPropertyHasTypedEntitySet), 10);
				createElementLinkMap.Add(typeof(EntityModelHasDomainTypes), 11);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new EntityModelHasPersistentTypes(partition, roleAssignments, propertyAssignments);
				case 1: return new InterfaceInheritInterfaces(partition, roleAssignments, propertyAssignments);
				case 2: return new EntityBaseHasBaseType(partition, roleAssignments, propertyAssignments);
				case 3: return new StructurePropertyHasType(partition, roleAssignments, propertyAssignments);
				case 4: return new PersistentTypeHasProperties(partition, roleAssignments, propertyAssignments);
				case 5: return new PersistentTypeHasNavigationProperties(partition, roleAssignments, propertyAssignments);
				// A constructor was not generated for PersistentTypeHasAssociations because it had HasCustomConstructor
				// set to true. Please provide the constructor below.
				case 6: return new PersistentTypeHasAssociations(partition, roleAssignments, propertyAssignments);
				case 7: return new NavigationPropertyHasAssociation(partition, roleAssignments, propertyAssignments);
				case 8: return new TypedEntitySetHasItemType(partition, roleAssignments, propertyAssignments);
				case 9: return new InterfaceHasIndexes(partition, roleAssignments, propertyAssignments);
				case 10: return new NavigationPropertyHasTypedEntitySet(partition, roleAssignments, propertyAssignments);
				case 11: return new EntityModelHasDomainTypes(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DONetEntityModelDesignerDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DONetEntityModelDesignerDomainModel.resourceManager == null)
				{
					DONetEntityModelDesignerDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DONetEntityModelDesignerDomainModel).Assembly);
				}
				return DONetEntityModelDesignerDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DONetEntityModelDesignerDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DONetEntityModelDesignerDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DONetEntityModelDesignerDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DONetEntityModelDesignerCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DONetEntityModelDesignerDomainModel.copyClosure = copyFilter;
				}
				return DONetEntityModelDesignerDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DONetEntityModelDesignerDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DONetEntityModelDesignerDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DONetEntityModelDesignerDomainModel.removeClosure = removeFilter;
				}
				return DONetEntityModelDesignerDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DONetEntityModelDesignerDeleteClosure : DONetEntityModelDesignerDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DONetEntityModelDesignerDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DONetEntityModelDesignerDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DONetEntityModelDesignerDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModelHasPersistentTypes.ElementDomainRoleId, true);
			DomainRoles.Add(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasProperties.PersistentTypeDomainRoleId, true);
			DomainRoles.Add(global::TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeHasNavigationProperties.PersistentTypeOfNavigationPropertyDomainRoleId, true);
			DomainRoles.Add(global::TXSoftware.DataObjectsNetEntityModel.Dsl.NavigationPropertyHasAssociation.NavigationPropertyDomainRoleId, true);
			DomainRoles.Add(global::TXSoftware.DataObjectsNetEntityModel.Dsl.InterfaceHasIndexes.InterfaceOfIndexDomainRoleId, true);
			DomainRoles.Add(global::TXSoftware.DataObjectsNetEntityModel.Dsl.EntityModelHasDomainTypes.DomainTypeDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DONetEntityModelDesignerCopyClosure : DONetEntityModelDesignerCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DONetEntityModelDesignerCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DONetEntityModelDesignerCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DONetEntityModelDesignerCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainEnumeration: AccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum AccessModifier
	{
		/// <summary>
		/// Internal
		/// Description for TXSoftware.DataObjectsNetEntityModel.Dsl.AccessModifier.Internal
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.AccessModifier/Internal.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Internal = 0,
		/// <summary>
		/// Public
		/// Description for TXSoftware.DataObjectsNetEntityModel.Dsl.AccessModifier.Public
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.AccessModifier/Public.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Public = 1,
	}
}
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainEnumeration: RequiredValue
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum RequiredValue
	{
	}
}
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainEnumeration: PropertyKind
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PropertyKind
	{
		/// <summary>
		/// Scalar
		/// Description for TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyKind.Scalar
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyKind/Scalar.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Scalar = 0,
		/// <summary>
		/// Structure
		/// Description for TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyKind.Structure
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyKind/Structure.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Structure = 1,
		/// <summary>
		/// Navigation
		/// Description for TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyKind.Navigation
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PropertyKind/Navigation.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Navigation = 2,
	}
}
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainEnumeration: PersistentTypeKind
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PersistentTypeKind
	{
		/// <summary>
		/// Interface
		/// Description for
		/// TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind.Interface
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind/Interface.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Interface = 0,
		/// <summary>
		/// Entity
		/// Description for
		/// TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind.Entity
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind/Entity.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Entity = 1,
		/// <summary>
		/// Structure
		/// Description for
		/// TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind.Structure
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind/Structure.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Structure = 2,
		/// <summary>
		/// ExternalType
		/// Description for
		/// TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind.ExternalType
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind/ExternalType.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		ExternalType = 3,
		/// <summary>
		/// TypedEntitySet
		/// Description for
		/// TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind.TypedEntitySet
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.PersistentTypeKind/TypedEntitySet.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		TypedEntitySet = 4,
	}
}
namespace TXSoftware.DataObjectsNetEntityModel.Dsl
{
	/// <summary>
	/// DomainEnumeration: InheritanceModifiers
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum InheritanceModifiers
	{
		/// <summary>
		/// None
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceModifiers/None.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		None = 0,
		/// <summary>
		/// Abstract
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceModifiers/Abstract.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Abstract = 1,
		/// <summary>
		/// Sealed
		/// Description for
		/// TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceModifiers.Sealed
		/// </summary>
		[DslDesign::DescriptionResource("TXSoftware.DataObjectsNetEntityModel.Dsl.InheritanceModifiers/Sealed.Description", typeof(global::TXSoftware.DataObjectsNetEntityModel.Dsl.DONetEntityModelDesignerDomainModel), "TXSoftware.DataObjectsNetEntityModel.Dsl.GeneratedCode.DomainModelResx")]
		Sealed = 2,
	}
}

