//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Xtensive.Core;
using Xtensive.Orm;
namespace Model.Version1_0_5_0.Entities
{
    [Xtensive.Orm.HierarchyRoot]
    [Xtensive.Orm.Index("Name",Unique=true,Name="idxName")]
    [Xtensive.Orm.Index("Age:DESC")]
    [System.SerializableAttribute]
    public partial class EntityBaseWithHistory: EntityBase,Model.Version1_0_5_0.Interfaces.IEntityWithHistory
    {
        
        #region Scalar Properties
        
        [Xtensive.Orm.Field]
        [Xtensive.Orm.Key(Position=5)]
        public virtual int Id
        {
            get;
            private set;
        }
        
        [Xtensive.Orm.Field(DefaultValue=null,Indexed=true,LazyLoad=true,Length=512,NullableOnUpgrade=true)]
        [Xtensive.Orm.FieldMapping("sMore")]
        [Xtensive.Orm.Version(Xtensive.Orm.VersionMode.Auto)]
        [Xtensive.Orm.TypeDiscriminator]
        [Xtensive.Orm.Validation.EmailConstraint(Mode=Xtensive.Orm.Validation.ConstrainMode.OnSetValue,Message="Email is invalid")]
        [Xtensive.Orm.Validation.LengthConstraint(Mode=Xtensive.Orm.Validation.ConstrainMode.OnValidate,Message="Length is invalid",Min=0,Max=400)]
        [Xtensive.Orm.Validation.NotEmptyConstraint]
        [Xtensive.Orm.Validation.NotNullConstraint]
        [Xtensive.Orm.Validation.NotNullOrEmptyConstraint]
        internal virtual string More
        {
            get;
            set;
        }
        
        #endregion Scalar Properties
        
        #region Navigation Properties
        
        [Xtensive.Orm.Field]
        [Xtensive.Orm.Association(PairTo="Owner")]
        public virtual Model.Version1_0_5_0.TypedEntitySets.HistoryEntitySet HistoryItems
        {
            get;
            private set;
        }
        
        #endregion Navigation Properties
        
        #region Constructors
        
        public EntityBaseWithHistory(Xtensive.Orm.Session session) : base(session)
        {}
        
        public EntityBaseWithHistory()
        {}
        public EntityBaseWithHistory(Xtensive.Orm.Session session,int id) : base(session,id)
        {}
        protected EntityBaseWithHistory(Xtensive.Orm.Session session,int id, params System.Object[] values) : base(session,id, values)
        {}
        
        #endregion Constructors
        
    }
}
