//------------------------------------------------------------------------------
// <auto-generated>
//     DataObjects.Net Entity Model Designer
//     Template version: 1.0.5.0
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Xtensive.Core;
using Xtensive.Orm;
namespace Model.Version1_0_5_0.TypedEntitySets
{
    [System.SerializableAttribute]
    public partial class HistoryEntitySet: Xtensive.Orm.EntitySet<Model.Version1_0_5_0.Interfaces.IHistory>
    {
        
        #region Constructors
        
        protected HistoryEntitySet(Xtensive.Orm.Entity owner, Xtensive.Orm.Model.FieldInfo field) : base(owner, field)
        {}
        
        protected HistoryEntitySet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : base(info, context)
        {}
        
        #endregion Constructors
        
    }
}
